---
title: "Data analysis"
output:
  html_document:
    df_print: paged
---

```{r}
# Require packages
library(tidyverse)
library(lme4)
library(lmerTest)
library(car)
library(MASS)

# Load data
data.frame <- read.csv("data.frame.csv")



```

# Distributive participants: Baseline \> 50%

## all 4 levels

```{r}



df.distributive.1 <- data.frame %>% 
  filter(participant.group == "Baseline > 50%") %>% 
  mutate(Condition = factor(Condition,
                            levels = c("Distributive", "Cumulative", "Baseline", "Control")))

contrasts(df.distributive.1$Condition)


```

```{r}

# First attempt
# Model with (1+Condition|Schedule.ID) + (1+Condition|Trial.Number)
# Causes singular fit

model1.1 <- glmer(distributive.target ~ Condition + 
                  (1+Condition|Schedule.ID) + (1+Condition|Trial.Number), 
                family = binomial(link = logit), 
                data = df.distributive.1, 
                control = glmerControl(optimizer = "bobyqa",
                                       optCtrl = list(maxfun = 100000)))
isSingular(model1.1, tol=1e-05)
Anova(model1.1)

```

```{r}

# Second attempt
# Model with (1+Condition|Schedule.ID) + (1+Condition||Trial.Number)
# Causes singular fit

model1.2 <- glmer(distributive.target ~ Condition + 
                  (1+Condition|Schedule.ID) +
                    (1+Condition||Trial.Number), 
                family = binomial(link = logit), 
                data = df.distributive.1, 
                control = glmerControl(optimizer = "bobyqa",
                                       optCtrl = list(maxfun = 100000)))
isSingular(model1.2, tol=1e-05)
Anova(model1.2)
```

```{r}

# Third attempt
# Model with (1+Condition|Schedule.ID) + (1|Trial.Number) 
# Causes singular fit

model1.3 <- glmer(distributive.target ~ Condition + 
                  (1+Condition|Schedule.ID) + (1|Trial.Number),
                family = binomial(link = logit), 
                data = df.distributive.1, 
                control = glmerControl(optimizer = "bobyqa",
                                     optCtrl = list(maxfun = 100000)))
isSingular(model1.3, tol=1e-05)
Anova(model1.3)

```

```{r}
summary(model1.3)
```

```{r}

# Fourth attempt
# Model with (1+Condition|Schedule.ID) 
# Causes singular fit

model1.4 <- glmer(distributive.target ~ Condition +
                  (1+Condition|Schedule.ID), 
                family = binomial(link = logit), 
                data = df.distributive.1, 
                control = glmerControl(optimizer = "bobyqa",
                                       optCtrl = list(maxfun = 100000)))
isSingular(model1.4, tol=1e-05)
Anova(model1.4)



```

```{r}

# Fifth attempt
# Model with (1+Condition||Schedule.ID) 
# Causes singular fit

model1.5 <- glmer(distributive.target ~ Condition +
                  (1+Condition||Schedule.ID), 
                family = binomial(link = logit), 
                data = df.distributive.1, 
                control = glmerControl(optimizer = "bobyqa",
                                       optCtrl = list(maxfun = 100000)))
isSingular(model1.5, tol=1e-05)
Anova(model1.5)

```

```{r}

# Sixth attempt
# Model with (1|Schedule.ID) + (1|Trial.Number)
# Causes singular fit

model1.6 <- glmer(distributive.target ~ Condition +
                  (1|Schedule.ID) + (1|Trial.Number),
                family = binomial(link = logit), 
                data = df.distributive.1, 
                control = glmerControl(optimizer = "bobyqa",
                                       optCtrl = list(maxfun = 100000)))
isSingular(model1.6, tol=1e-05)
Anova(model1.6)


```

```{r}

# Seventh attempt
# Model with (1|Schedule.ID)
# Causes singular fit

model1.7 <- glmer(distributive.target ~ Condition +
                  (1|Schedule.ID),
                family = binomial(link = logit), 
                data = df.distributive.1, 
                control = glmerControl(optimizer = "bobyqa",
                                       optCtrl = list(maxfun = 100000)))
isSingular(model1.7, tol=1e-05)
Anova(model1.7)


```

```{r}
summary(model1.7)

```

# Distributive participants: Baseline \> 50%

## 3 levels

```{r}


df.distributive.2 <- data.frame %>% 
  filter(participant.group == "Baseline > 50%") %>% 
  filter(Condition != "Control") %>% 
  mutate(Condition = factor(Condition,
                            levels = c("Distributive", "Cumulative", "Baseline")))

contrasts(df.distributive.1$Condition)
```

```{r}

# First attempt
# Model with (1+Condition|Schedule.ID) + (1+Condition|Trial.Number)
# Causes singular fit

model2.1 <- glmer(distributive.target ~ Condition + 
                  (1+Condition|Schedule.ID) + (1+Condition|Trial.Number), 
                family = binomial(link = logit), 
                data = df.distributive.2, 
                control = glmerControl(optimizer = "bobyqa",
                                       optCtrl = list(maxfun = 100000)))
isSingular(model2.1, tol=1e-05)
Anova(model2.1)

```

```{r}
# Second attempt
# Model with (1+Condition|Schedule.ID) + (1+Condition||Trial.Number)
# Causes singular fit

model2.2 <- glmer(distributive.target ~ Condition + 
                  (1+Condition|Schedule.ID) +
                    (1+Condition||Trial.Number), 
                family = binomial(link = logit), 
                data = df.distributive.2, 
                control = glmerControl(optimizer = "bobyqa",
                                       optCtrl = list(maxfun = 100000)))
isSingular(model2.2, tol=1e-05)
Anova(model2.2)
```

```{r}

# Third attempt
# Model with (1+Condition|Schedule.ID) + (1|Trial.Number) 
# Causes singular fit

model2.3 <- glmer(distributive.target ~ Condition + 
                  (1+Condition|Schedule.ID) + (1|Trial.Number),
                family = binomial(link = logit), 
                data = df.distributive.2, 
                control = glmerControl(optimizer = "bobyqa",
                                     optCtrl = list(maxfun = 100000)))
isSingular(model2.3, tol=1e-05)
Anova(model2.3)
```

```{r}
summary(model2.3)
```
